import { type Placement } from '../types';

/**
 * Canonical editable placement overrides for Estella nodes.
 *
 * The node inventory can carry a coarse placement so the tree remains readable, but exact
 * spatial data should live here. Add records by stable node id as authored values become
 * known. This lets future edits touch one small file instead of the whole content tree.
 */
export const ESTELLA_PLACEMENTS: Partial<Record<string, Placement>> = {
  // Example shape for a circular stellar orbit:
  // 'estella-iii': {
  //   kind: 'orbit',
  //   parentId: 'estella',
  //   usage: 'stellar',
  //   orbit: {
  //     kind: 'circular',
  //     radius: 150_000_000_000,
  //     epochAngle: 0,
  //     epochTime: 0,
  //     orbitSense: 1,
  //     period: 31_557_600,
  //   },
  // },

  // Example shape for a non-circular cluster orbit:
  // 'belt-cluster-wreckage-field': {
  //   kind: 'orbit',
  //   parentId: 'estella',
  //   usage: 'eccentric',
  //   orbit: {
  //     kind: 'keplerian',
  //     semiMajorAxis: 420_000_000_000,
  //     eccentricity: 0.18,
  //     argumentOfPeriapsis: 1.1,
  //     meanAnomalyAtEpoch: 0.4,
  //     epochTime: 0,
  //     orbitSense: 1,
  //   },
  // },

  'estella-i': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 240_000_000, epochAngle: -0.7, epochTime: 0, orbitSense: 1, period: 310_200 },
  },
  'estella-i-low-orbit-station': {
    kind: 'orbit',
    parentId: 'estella-i',
    usage: 'low',
    orbit: { kind: 'circular', radius: 225_000, altitude: 75_000, epochAngle: 0.2, epochTime: 0, orbitSense: 1, period: 2_300 },
  },
  'estella-i-worker-hab': { kind: 'surface', parentId: 'estella-i', angle: -2.2, side: 'night' },
  'estella-i-refractory-mine': { kind: 'surface', parentId: 'estella-i', angle: -0.2, side: 'terminator' },
  'estella-i-hot-processing': { kind: 'surface', parentId: 'estella-i', angle: 0.35, side: 'terminator' },
  'estella-i-deep-listening': { kind: 'surface', parentId: 'estella-i', angle: 2.55, side: 'night' },

  'estella-ii': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 440_000_000, epochAngle: 0.65, epochTime: 0, orbitSense: 1, period: 770_100 },
  },
  'estella-ii-commercial-hub': {
    kind: 'orbit',
    parentId: 'estella-ii',
    usage: 'low',
    orbit: { kind: 'circular', radius: 620_000, altitude: 300_000, epochAngle: -0.25, epochTime: 0, orbitSense: 1, period: 3_000 },
  },
  'estella-ii-olympos-platform': { kind: 'surface', parentId: 'estella-ii', angle: -0.8, altitude: 55_000, side: 'unspecified' },
  'estella-ii-olympos': { kind: 'surface', parentId: 'estella-ii', angle: -0.8, altitude: 55_000, side: 'unspecified' },
  'estella-ii-nimbus-crucible-platform': { kind: 'surface', parentId: 'estella-ii', angle: 0.35, altitude: 34_000, side: 'unspecified' },
  'estella-ii-nimbus-crucible': { kind: 'surface', parentId: 'estella-ii', angle: 0.35, altitude: 34_000, side: 'unspecified' },
  'estella-ii-pandemonium': { kind: 'surface', parentId: 'estella-ii', angle: -1.35, side: 'unspecified' },

  'estella-iii': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 680_000_000, epochAngle: 1.45, epochTime: 0, orbitSense: 1, period: 1_479_600 },
  },
  'estella-iii-main-customs-station': {
    kind: 'orbit',
    parentId: 'estella-iii',
    usage: 'low',
    orbit: { kind: 'circular', radius: 500_000, altitude: 140_000, epochAngle: -0.15, epochTime: 0, orbitSense: 1, period: 2_000 },
  },
  'estella-iii-luxury-habitat': {
    kind: 'orbit',
    parentId: 'estella-iii',
    usage: 'high',
    orbit: { kind: 'circular', radius: 760_000, altitude: 400_000, epochAngle: 1.75, epochTime: 0, orbitSense: 1, period: 3_700 },
  },
  'estella-iii-capital-city': { kind: 'surface', parentId: 'estella-iii', angle: 0.1, side: 'equatorial' },
  'estella-iii-finance-city': { kind: 'surface', parentId: 'estella-iii', angle: 0.7, side: 'equatorial' },
  'estella-iii-high-tech-city': { kind: 'surface', parentId: 'estella-iii', angle: 1.35, side: 'equatorial' },
  'estella-iii-coastal-resort': { kind: 'surface', parentId: 'estella-iii', angle: 2.05, side: 'equatorial' },
  'estella-iii-agricultural-region': { kind: 'surface', parentId: 'estella-iii', angle: 2.85, side: 'equatorial' },
  'estella-iii-polar-science': { kind: 'surface', parentId: 'estella-iii', angle: -2.55, side: 'polar' },
  'estella-iii-military-spaceport': { kind: 'surface', parentId: 'estella-iii', angle: -1.3, side: 'unspecified' },
  'estella-iii-historic-site': { kind: 'surface', parentId: 'estella-iii', angle: -0.55, side: 'equatorial' },

  'estella-iiia': {
    kind: 'orbit',
    parentId: 'estella-iii',
    usage: 'moon',
    orbit: { kind: 'circular', radius: 2_200_000, epochAngle: 2.4, epochTime: 0, orbitSense: 1, period: 18_400 },
  },
  'estella-iiia-main-port': {
    kind: 'orbit',
    parentId: 'estella-iiia',
    usage: 'low',
    orbit: { kind: 'circular', radius: 205_000, altitude: 65_000, epochAngle: 0.6, epochTime: 0, orbitSense: 1, period: 3_300 },
  },
  'estella-iiia-helium-mining': { kind: 'surface', parentId: 'estella-iiia', angle: -0.85, side: 'equatorial' },
  'estella-iiia-science-settlement': { kind: 'surface', parentId: 'estella-iiia', angle: 1.6, side: 'equatorial' },
  'estella-iiia-heritage-site': { kind: 'surface', parentId: 'estella-iiia', angle: 2.8, side: 'equatorial' },

  'estella-iv': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 960_000_000, epochAngle: -2.25, epochTime: 0, orbitSense: 1, period: 2_482_000 },
  },
  'estella-iv-main-station': {
    kind: 'orbit',
    parentId: 'estella-iv',
    usage: 'low',
    orbit: { kind: 'circular', radius: 485_000, altitude: 140_000, epochAngle: 0.9, epochTime: 0, orbitSense: 1, period: 2_000 },
  },
  'estella-iv-primary-city': { kind: 'surface', parentId: 'estella-iv', angle: -0.1, side: 'equatorial' },
  'estella-iv-climate-poi-1': { kind: 'surface', parentId: 'estella-iv', angle: 1.15, side: 'equatorial' },
  'estella-iv-climate-poi-2': { kind: 'surface', parentId: 'estella-iv', angle: 2.45, side: 'equatorial' },
  'estella-iv-climate-poi-3': { kind: 'surface', parentId: 'estella-iv', angle: -2.0, side: 'equatorial' },

  'estella-v': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 1_140_000_000, epochAngle: -0.35, epochTime: 0, orbitSense: 1, period: 3_218_000 },
  },
  'estella-v-transit-station': {
    kind: 'orbit',
    parentId: 'estella-v',
    usage: 'low',
    orbit: { kind: 'circular', radius: 390_000, altitude: 110_000, epochAngle: 0.45, epochTime: 0, orbitSense: 1, period: 2_700 },
  },
  'estella-v-orbital-factory': {
    kind: 'orbit',
    parentId: 'estella-v',
    usage: 'high',
    orbit: { kind: 'circular', radius: 620_000, altitude: 340_000, epochAngle: -1.1, epochTime: 0, orbitSense: 1, period: 5_400 },
  },
  'estella-v-capital-settlement': { kind: 'surface', parentId: 'estella-v', angle: 0.15, side: 'equatorial' },
  'estella-v-open-cast-mine': { kind: 'surface', parentId: 'estella-v', angle: 1.1, side: 'equatorial' },
  'estella-v-atmo-refinery': { kind: 'surface', parentId: 'estella-v', angle: 2.05, side: 'equatorial' },
  'estella-v-storm-research': { kind: 'surface', parentId: 'estella-v', angle: -2.35, side: 'unspecified' },
  'estella-v-abandoned-colony': { kind: 'surface', parentId: 'estella-v', angle: -0.85, side: 'unspecified' },

  'estella-va': {
    kind: 'orbit',
    parentId: 'estella-v',
    usage: 'moon',
    orbit: { kind: 'circular', radius: 1_100_000, epochAngle: 2.25, epochTime: 0, orbitSense: 1, period: 12_500 },
  },
  'estella-va-ore-depot': {
    kind: 'orbit',
    parentId: 'estella-va',
    usage: 'low',
    orbit: { kind: 'circular', radius: 130_000, altitude: 45_000, epochAngle: -0.25, epochTime: 0, orbitSense: 1, period: 2_900 },
  },
  'estella-va-strip-mine': { kind: 'surface', parentId: 'estella-va', angle: -0.45, side: 'equatorial' },
  'estella-va-miner-hab': { kind: 'surface', parentId: 'estella-va', angle: 1.8, side: 'equatorial' },

  'estella-vi': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 1_250_000_000, epochAngle: 0.95, epochTime: 0, orbitSense: 1, period: 3_694_000 },
  },
  'estella-vi-main-dispatch': {
    kind: 'orbit',
    parentId: 'estella-vi',
    usage: 'low',
    orbit: { kind: 'circular', radius: 490_000, altitude: 160_000, epochAngle: 0.3, epochTime: 0, orbitSense: 1, period: 2_300 },
  },
  'estella-vi-heavy-cargo-dispatch': {
    kind: 'orbit',
    parentId: 'estella-vi',
    usage: 'high',
    orbit: { kind: 'circular', radius: 820_000, altitude: 490_000, epochAngle: -1.4, epochTime: 0, orbitSense: 1, period: 5_000 },
  },
  'estella-vi-industrial-city': { kind: 'surface', parentId: 'estella-vi', angle: -0.15, side: 'equatorial' },
  'estella-vi-foundry-complex': { kind: 'surface', parentId: 'estella-vi', angle: 0.95, side: 'equatorial' },
  'estella-vi-spaceport': { kind: 'surface', parentId: 'estella-vi', angle: 1.85, side: 'equatorial' },
  'estella-vi-agricultural-lowlands': { kind: 'surface', parentId: 'estella-vi', angle: 2.7, side: 'equatorial' },
  'estella-vi-polar-weather-research': { kind: 'surface', parentId: 'estella-vi', angle: -2.55, side: 'polar' },
  'estella-vi-mountain-mining': { kind: 'surface', parentId: 'estella-vi', angle: -1.25, altitude: 4_000, side: 'unspecified' },

  'estella-via': {
    kind: 'orbit',
    parentId: 'estella-vi',
    usage: 'moon',
    orbit: { kind: 'circular', radius: 1_250_000, epochAngle: 2.7, epochTime: 0, orbitSense: 1, period: 13_000 },
  },
  'estella-via-drydock': {
    kind: 'orbit',
    parentId: 'estella-via',
    usage: 'low',
    orbit: { kind: 'circular', radius: 145_000, altitude: 50_000, epochAngle: 0.8, epochTime: 0, orbitSense: 1, period: 3_100 },
  },
  'estella-via-component-supply': {
    kind: 'orbit',
    parentId: 'estella-via',
    usage: 'high',
    orbit: { kind: 'circular', radius: 230_000, altitude: 135_000, epochAngle: -1.2, epochTime: 0, orbitSense: 1, period: 6_200 },
  },
  'estella-via-surface-anchor': { kind: 'surface', parentId: 'estella-via', angle: 0.35, side: 'equatorial' },
  'estella-via-rare-alloy-extraction': { kind: 'surface', parentId: 'estella-via', angle: -2.2, side: 'equatorial' },

  'estella-vib': {
    kind: 'orbit',
    parentId: 'estella-vi',
    usage: 'moon',
    orbit: { kind: 'circular', radius: 1_650_000, epochAngle: -2.05, epochTime: 0, orbitSense: 1, period: 19_900 },
  },
  'estella-vib-cold-chain-transit': {
    kind: 'orbit',
    parentId: 'estella-vib',
    usage: 'low',
    orbit: { kind: 'circular', radius: 122_000, altitude: 42_000, epochAngle: 0.4, epochTime: 0, orbitSense: 1, period: 3_500 },
  },
  'estella-vib-vat-protein': { kind: 'surface', parentId: 'estella-vib', angle: -0.25, side: 'equatorial' },
  'estella-vib-pharma-horticulture': { kind: 'surface', parentId: 'estella-vib', angle: 1.45, side: 'equatorial' },
  'estella-vib-aquaculture': { kind: 'surface', parentId: 'estella-vib', angle: 2.65, side: 'equatorial' },

  'estella-vii': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: { kind: 'circular', radius: 1_350_000_000, epochAngle: -1.7, epochTime: 0, orbitSense: 1, period: 4_145_000 },
  },
  'estella-vii-transit-station': {
    kind: 'orbit',
    parentId: 'estella-vii',
    usage: 'low',
    orbit: { kind: 'circular', radius: 235_000, altitude: 65_000, epochAngle: -0.6, epochTime: 0, orbitSense: 1, period: 2_900 },
  },
  'estella-vii-high-vacuum-factory': { kind: 'surface', parentId: 'estella-vii', angle: 0.25, side: 'equatorial' },
  'estella-vii-feedstock-mine': { kind: 'surface', parentId: 'estella-vii', angle: 1.55, side: 'equatorial' },
  'estella-vii-worker-hab': { kind: 'surface', parentId: 'estella-vii', angle: -1.25, side: 'equatorial' },
  'estella-vii-black-project-outpost': { kind: 'surface', parentId: 'estella-vii', angle: -2.6, side: 'unspecified' },

  'belt-cluster-near': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'co-orbital',
    orbit: { kind: 'circular', radius: 1_520_000_000, epochAngle: 0.2, epochTime: 0, orbitSense: 1, period: 4_370_000 },
  },
  'caravanserai': { kind: 'cluster-member', parentId: 'belt-cluster-near', x: 0, y: 0 },
  'the-still': { kind: 'cluster-member', parentId: 'belt-cluster-near', x: 42_000, y: -18_000 },
  'prospect-rock-es-c-0101': { kind: 'cluster-member', parentId: 'belt-cluster-near', x: -26_000, y: 22_000 },
  'survey-rock-es-s-0101': { kind: 'cluster-member', parentId: 'belt-cluster-near', x: 24_000, y: 33_000 },

  'estella-viii': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: {
      kind: 'circular',
      radius: 1_570_000_000,
      epochAngle: 2.1,
      epochTime: 0,
      orbitSense: 1,
      period: 4_559_700,
    },
  },
  'estella-viii-friendly-station': {
    kind: 'orbit',
    parentId: 'estella-viii',
    usage: 'low',
    orbit: {
      kind: 'circular',
      radius: 260_000,
      altitude: 80_000,
      epochAngle: 0.4,
      epochTime: 0,
      orbitSense: 1,
      period: 3_500,
    },
  },
  'estella-viii-high-station': {
    kind: 'orbit',
    parentId: 'estella-viii',
    usage: 'high',
    orbit: {
      kind: 'circular',
      radius: 420_000,
      altitude: 240_000,
      epochAngle: -1.2,
      epochTime: 0,
      orbitSense: 1,
      period: 7_300,
    },
  },
  'estella-viii-captured-moonlet': {
    kind: 'orbit',
    parentId: 'estella-viii',
    usage: 'moon',
    orbit: {
      kind: 'circular',
      radius: 640_000,
      epochAngle: 1.6,
      epochTime: 0,
      orbitSense: 1,
      period: 13_700,
    },
  },
  'estella-viii-settlement': {
    kind: 'surface',
    parentId: 'estella-viii',
    angle: 0.15,
    side: 'equatorial',
  },
  'estella-viii-mining-site': {
    kind: 'surface',
    parentId: 'estella-viii',
    angle: 2.35,
    side: 'equatorial',
  },
  'estella-viii-abandoned-site': {
    kind: 'surface',
    parentId: 'estella-viii',
    angle: -1.7,
    side: 'unspecified',
  },

  'estella-ix': {
    kind: 'orbit',
    parentId: 'estella',
    usage: 'stellar',
    orbit: {
      kind: 'circular',
      radius: 1_585_000_000,
      epochAngle: 2.95,
      epochTime: 0,
      orbitSense: 1,
      period: 4_616_800,
    },
  },
  'estella-ix-research-station': {
    kind: 'orbit',
    parentId: 'estella-ix',
    usage: 'low',
    orbit: {
      kind: 'circular',
      radius: 240_000,
      altitude: 75_000,
      epochAngle: -0.35,
      epochTime: 0,
      orbitSense: 1,
      period: 3_700,
    },
  },
  'estella-ix-supply-depot': {
    kind: 'orbit',
    parentId: 'estella-ix',
    usage: 'high',
    orbit: {
      kind: 'circular',
      radius: 390_000,
      altitude: 225_000,
      epochAngle: 1.05,
      epochTime: 0,
      orbitSense: 1,
      period: 7_700,
    },
  },
  'estella-ix-captured-moonlet': {
    kind: 'orbit',
    parentId: 'estella-ix',
    usage: 'moon',
    orbit: {
      kind: 'circular',
      radius: 600_000,
      epochAngle: -1.75,
      epochTime: 0,
      orbitSense: 1,
      period: 14_700,
    },
  },
  'estella-ix-research-base': {
    kind: 'surface',
    parentId: 'estella-ix',
    angle: 0.55,
    side: 'equatorial',
  },
  'estella-ix-ice-mine': {
    kind: 'surface',
    parentId: 'estella-ix',
    angle: 2.75,
    side: 'equatorial',
  },
  'estella-ix-geological-feature': {
    kind: 'surface',
    parentId: 'estella-ix',
    angle: -1.15,
    side: 'unspecified',
  },

  // The Wells
  'estella-x': { kind: 'orbit', parentId: 'estella', usage: 'stellar', orbit: { kind: 'circular', radius: 1_950_000_000, epochAngle: -2.4, epochTime: 0, orbitSense: 1, period: 6_400_000 } },
  'estella-x-skim-hub': { kind: 'orbit', parentId: 'estella-x', usage: 'high', orbit: { kind: 'circular', radius: 1_020_000, altitude: 220_000, epochAngle: 0.35, epochTime: 0, orbitSense: 1, period: 4_800 } },
  'estella-xa': { kind: 'orbit', parentId: 'estella-x', usage: 'moon', orbit: { kind: 'circular', radius: 3_200_000, epochAngle: 0.8, epochTime: 0, orbitSense: 1, period: 38_000 } },
  'estella-xb': { kind: 'orbit', parentId: 'estella-x', usage: 'moon', orbit: { kind: 'circular', radius: 4_650_000, epochAngle: 2.2, epochTime: 0, orbitSense: 1, period: 66_000 } },
  'estella-xc': { kind: 'orbit', parentId: 'estella-x', usage: 'moon', orbit: { kind: 'circular', radius: 6_100_000, epochAngle: -1.4, epochTime: 0, orbitSense: 1, period: 98_000 } },
  'estella-xd': { kind: 'orbit', parentId: 'estella-x', usage: 'moon', orbit: { kind: 'circular', radius: 8_000_000, epochAngle: -2.7, epochTime: 0, orbitSense: 1, period: 147_000 } },
  'estella-xc-transit-refuel-station': { kind: 'orbit', parentId: 'estella-xc', usage: 'low', orbit: { kind: 'circular', radius: 118_000, altitude: 42_000, epochAngle: 0.6, epochTime: 0, orbitSense: 1, period: 3_600 } },
  'estella-xd-orbital-chem-station': { kind: 'orbit', parentId: 'estella-xd', usage: 'low', orbit: { kind: 'circular', radius: 152_000, altitude: 52_000, epochAngle: -0.75, epochTime: 0, orbitSense: 1, period: 3_800 } },
  'estella-x-trojan-captive': { kind: 'orbit', parentId: 'estella-x', usage: 'high', orbit: { kind: 'circular', radius: 11_500_000, epochAngle: 1.55, epochTime: 0, orbitSense: 1, period: 250_000 } },
  'estella-xa-volatiles-transit': { kind: 'surface', parentId: 'estella-xa', angle: 0.25, side: 'equatorial' },
  'estella-xa-deep-ice-mine': { kind: 'surface', parentId: 'estella-xa', angle: 1.7, side: 'equatorial' },
  'estella-xa-exobiology-research': { kind: 'surface', parentId: 'estella-xa', angle: -2.35, side: 'unspecified' },
  'estella-xb-rare-element-mine': { kind: 'surface', parentId: 'estella-xb', angle: -0.45, side: 'equatorial' },
  'estella-xb-smelting-processing': { kind: 'surface', parentId: 'estella-xb', angle: 1.15, side: 'equatorial' },
  'estella-xb-worker-hab': { kind: 'surface', parentId: 'estella-xb', angle: 2.65, side: 'equatorial' },
  'estella-xc-main-outpost': { kind: 'surface', parentId: 'estella-xc', angle: 0.9, side: 'equatorial' },
  'estella-xd-geothermal-extraction': { kind: 'surface', parentId: 'estella-xd', angle: -1.2, side: 'equatorial' },

  'estella-xi': { kind: 'orbit', parentId: 'estella', usage: 'stellar', orbit: { kind: 'circular', radius: 2_650_000_000, epochAngle: 1.1, epochTime: 0, orbitSense: 1, period: 10_200_000 } },
  'estella-xi-industrial-skim-hub': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 1_450_000, altitude: 300_000, epochAngle: -0.2, epochTime: 0, orbitSense: 1, period: 5_200 } },
  'estella-xi-observation-transit-nexus': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 1_900_000, altitude: 750_000, epochAngle: 1.45, epochTime: 0, orbitSense: 1, period: 7_800 } },
  'estella-xia': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 3_800_000, epochAngle: -0.7, epochTime: 0, orbitSense: 1, period: 35_000 } },
  'estella-xib': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 5_400_000, epochAngle: 0.95, epochTime: 0, orbitSense: 1, period: 59_000 } },
  'estella-xic': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 7_200_000, epochAngle: 2.3, epochTime: 0, orbitSense: 1, period: 91_000 } },
  'estella-xid': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 9_800_000, epochAngle: -2.1, epochTime: 0, orbitSense: 1, period: 145_000 } },
  'estella-xie': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 12_600_000, epochAngle: -0.05, epochTime: 0, orbitSense: 1, period: 210_000 } },
  'estella-xif': { kind: 'orbit', parentId: 'estella-xi', usage: 'moon', orbit: { kind: 'circular', radius: 15_800_000, epochAngle: 2.75, epochTime: 0, orbitSense: 1, period: 295_000 } },
  'estella-xia-orbital-chem-station': { kind: 'orbit', parentId: 'estella-xia', usage: 'low', orbit: { kind: 'circular', radius: 210_000, altitude: 70_000, epochAngle: 0.35, epochTime: 0, orbitSense: 1, period: 3_200 } },
  'estella-xic-research-station': { kind: 'orbit', parentId: 'estella-xic', usage: 'low', orbit: { kind: 'circular', radius: 172_000, altitude: 62_000, epochAngle: -1.15, epochTime: 0, orbitSense: 1, period: 3_900 } },
  'estella-xid-main-port-station': { kind: 'orbit', parentId: 'estella-xid', usage: 'low', orbit: { kind: 'circular', radius: 285_000, altitude: 85_000, epochAngle: 0.75, epochTime: 0, orbitSense: 1, period: 3_700 } },
  'estella-xi-captive-smuggler-deaddrop': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 18_500_000, epochAngle: 0.4, epochTime: 0, orbitSense: 1, period: 370_000 } },
  'estella-xi-captive-science-waypoint': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 20_200_000, epochAngle: 1.7, epochTime: 0, orbitSense: 1, period: 420_000 } },
  'estella-xi-captive-fence': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 22_000_000, epochAngle: -1.15, epochTime: 0, orbitSense: 1, period: 480_000 } },
  'estella-xi-captive-religious-retreat': { kind: 'orbit', parentId: 'estella-xi', usage: 'high', orbit: { kind: 'circular', radius: 24_000_000, epochAngle: -2.6, epochTime: 0, orbitSense: 1, period: 545_000 } },
  'estella-xia-sulfur-mine': { kind: 'surface', parentId: 'estella-xia', angle: 0.2, side: 'equatorial' },
  'estella-xia-sealed-worker-hab': { kind: 'surface', parentId: 'estella-xia', angle: 1.65, side: 'equatorial' },
  'estella-xia-rare-element-extraction': { kind: 'surface', parentId: 'estella-xia', angle: -2.25, side: 'equatorial' },
  'estella-xib-cryo-transit': { kind: 'surface', parentId: 'estella-xib', angle: -0.15, side: 'equatorial' },
  'estella-xib-methane-refinery': { kind: 'surface', parentId: 'estella-xib', angle: 0.85, side: 'equatorial' },
  'estella-xib-organic-chemistry': { kind: 'surface', parentId: 'estella-xib', angle: 1.75, side: 'equatorial' },
  'estella-xib-hydrocarbon-extraction': { kind: 'surface', parentId: 'estella-xib', angle: 2.65, side: 'equatorial' },
  'estella-xib-science-settlement': { kind: 'surface', parentId: 'estella-xib', angle: -2.4, side: 'unspecified' },
  'estella-xic-deep-ice-exobiology': { kind: 'surface', parentId: 'estella-xic', angle: 0.55, side: 'equatorial' },
  'estella-xic-ice-mining': { kind: 'surface', parentId: 'estella-xic', angle: 2.15, side: 'equatorial' },
  'estella-xid-services-outfitter-hangar': { kind: 'surface', parentId: 'estella-xid', angle: -0.35, side: 'equatorial' },
  'estella-xid-customs-transit': { kind: 'surface', parentId: 'estella-xid', angle: 1.15, side: 'equatorial' },
  'estella-xid-specialty-cargo': { kind: 'surface', parentId: 'estella-xid', angle: 2.55, side: 'equatorial' },
  'estella-xie-outer-spec-drydock': { kind: 'surface', parentId: 'estella-xie', angle: 0.35, side: 'equatorial' },
  'estella-xie-component-fabrication': { kind: 'surface', parentId: 'estella-xie', angle: 1.9, side: 'equatorial' },
  'estella-xie-rare-alloy-extraction': { kind: 'surface', parentId: 'estella-xie', angle: -2.05, side: 'equatorial' },
  'estella-xif-observatory': { kind: 'surface', parentId: 'estella-xif', angle: -0.65, side: 'equatorial' },
  'estella-xif-deep-listening-array': { kind: 'surface', parentId: 'estella-xif', angle: 1.2, side: 'equatorial' },
  'estella-xif-sealed-research-outpost': { kind: 'surface', parentId: 'estella-xif', angle: 2.7, side: 'unspecified' },

  'estella-xii': { kind: 'orbit', parentId: 'estella', usage: 'stellar', orbit: { kind: 'circular', radius: 3_550_000_000, epochAngle: -0.9, epochTime: 0, orbitSense: 1, period: 15_800_000 } },
  'estella-xii-observation-post-station': { kind: 'orbit', parentId: 'estella-xii', usage: 'high', orbit: { kind: 'circular', radius: 980_000, altitude: 260_000, epochAngle: 0.55, epochTime: 0, orbitSense: 1, period: 6_800 } },
  'estella-xiia': { kind: 'orbit', parentId: 'estella-xii', usage: 'moon', orbit: { kind: 'circular', radius: 3_200_000, epochAngle: 0.4, epochTime: 0, orbitSense: 1, period: 48_000 } },
  'estella-xiib': { kind: 'orbit', parentId: 'estella-xii', usage: 'moon', orbit: { kind: 'circular', radius: 4_900_000, epochAngle: 1.9, epochTime: 0, orbitSense: 1, period: 91_000 } },
  'estella-xiic': { kind: 'orbit', parentId: 'estella-xii', usage: 'moon', orbit: { kind: 'circular', radius: 7_600_000, epochAngle: -1.7, epochTime: 0, orbitSense: 1, period: 175_000 } },
  'estella-xiid': { kind: 'orbit', parentId: 'estella-xii', usage: 'moon', orbit: { kind: 'circular', radius: 10_500_000, epochAngle: 2.75, epochTime: 0, orbitSense: 1, period: 280_000 } },
  'estella-xiib-transit-station': { kind: 'orbit', parentId: 'estella-xiib', usage: 'low', orbit: { kind: 'circular', radius: 112_000, altitude: 42_000, epochAngle: -0.45, epochTime: 0, orbitSense: 1, period: 3_600 } },
  'estella-xii-captive-smuggler-waypoint': { kind: 'orbit', parentId: 'estella-xii', usage: 'high', orbit: { kind: 'circular', radius: 13_600_000, epochAngle: -0.25, epochTime: 0, orbitSense: 1, period: 405_000 } },
  'estella-xii-captive-comm-relay': { kind: 'orbit', parentId: 'estella-xii', usage: 'high', orbit: { kind: 'circular', radius: 15_400_000, epochAngle: 1.35, epochTime: 0, orbitSense: 1, period: 490_000 } },
  'estella-xiia-deep-ice-mine': { kind: 'surface', parentId: 'estella-xiia', angle: 0.15, side: 'equatorial' },
  'estella-xiia-volatiles-transit': { kind: 'surface', parentId: 'estella-xiia', angle: 1.55, side: 'equatorial' },
  'estella-xiia-isolated-settlement': { kind: 'surface', parentId: 'estella-xiia', angle: -2.45, side: 'unspecified' },
  'estella-xiib-outpost': { kind: 'surface', parentId: 'estella-xiib', angle: 0.7, side: 'equatorial' },
  'estella-xiic-isotope-mining': { kind: 'surface', parentId: 'estella-xiic', angle: -0.9, side: 'equatorial' },
  'estella-xiic-comet-research': { kind: 'surface', parentId: 'estella-xiic', angle: 1.9, side: 'equatorial' },
  'estella-xiid-black-project-exile': { kind: 'surface', parentId: 'estella-xiid', angle: -1.75, side: 'unspecified' },
};
