import type { MissionCargoSpec } from './mission-cost';

export type FragilityLevel = 'somewhat-fragile' | 'fragile' | 'very-fragile' | 'extremely-fragile';

export interface FragileCargoTerms {
  level: FragilityLevel;
  shockAbsorbingContainer: boolean;
  conditionRiskFraction: number;
}

export const FRAGILITY_LEVELS: Readonly<Record<FragilityLevel, { name: string; integrity: number; buffer: number }>> = {
  'somewhat-fragile': { name: 'Somewhat Fragile', integrity: 5, buffer: 1 },
  fragile: { name: 'Fragile', integrity: 4, buffer: 1 },
  'very-fragile': { name: 'Very Fragile', integrity: 3, buffer: 1 },
  'extremely-fragile': { name: 'Extremely Fragile', integrity: 2, buffer: 0 },
};

const FRAGILE_CARGO: Readonly<Record<string, FragileCargoTerms>> = {
  'acoustic fit-out kits': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'acoustic isolation kits': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'acoustic metamaterial stock': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'assay bench packages': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'boutique aquaculture trays': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'cabin liner panels': { level: 'somewhat-fragile', shockAbsorbingContainer: false, conditionRiskFraction: 0.35 },
  'calibrated joust drone swarms': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'Celadon-class client acceptance suite': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'ceramic flux precursors': { level: 'somewhat-fragile', shockAbsorbingContainer: false, conditionRiskFraction: 0.40 },
  'ceremonial armor cases': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'claim beacon kits': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'court wine and stasis delicacies': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'cruise-liner fixture stock': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'drive incident evidence locker': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'executive medicine lockers': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'exotic gift caskets': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'failed field regulator vault': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'field calibration service kits': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'field geometry control stack': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'house pennant transponder cores': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'incident review evidence crates': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'maintenance control cabinets': { level: 'fragile', shockAbsorbingContainer: false, conditionRiskFraction: 0.45 },
  'medical clinic lockers': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'medical cold-chain lockers': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'medical supplies': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'metric field coil cartridge': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'null-field stabilization crate': { level: 'extremely-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.70 },
  'panoramic viewport assemblies': { level: 'extremely-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.65 },
  'panoramic viewport rework assemblies': { level: 'extremely-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.65 },
  'pharmaceutical horticulture crates': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'phase-locked field regulator bank': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.65 },
  'polished cabin shrine modules': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'Porcelain-class warranty evidence crates': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'prestige ceramic feedstock': { level: 'somewhat-fragile', shockAbsorbingContainer: false, conditionRiskFraction: 0.40 },
  'propulsion diagnostics kits': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'prototype field regulator package': { level: 'extremely-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.70 },
  'quarantined controller returns': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'quarantined propulsion control stack': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'RCS installation kits': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'RCS thruster packages': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'reactor diagnostic isotopes': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.65 },
  'referee telemetry pylons': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'restricted civilian driveware crate': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'sealed accident telemetry core': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'sealed assay cores': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'sealed floral conservatory stock': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'sealed telemetry return lots': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'status banquet cold-chain': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'survey instrument crates': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'thermal tile lots': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'tilt-yard drone packs': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'tournament prizes and trophy engines': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'unproofed ceremonial armor': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.45 },
  'VHM warranty black-box vault': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.60 },
  'vibration isolation service kits': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'viewport crystal blanks': { level: 'extremely-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.70 },
  'viewport frame assemblies': { level: 'fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
  'warranty black-box packages': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.55 },
  'warranty recertification packages': { level: 'somewhat-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.40 },
  'weather telemetry cores': { level: 'very-fragile', shockAbsorbingContainer: true, conditionRiskFraction: 0.50 },
};

const ORDINARY_CARGO = new Set<string>([
  'academy verdict rolls',
  'acceptance mockup sections',
  'acid precursor drums',
  'acid-rated lift bearings',
  'airlock actuator assemblies',
  'alchemical reagent pallets',
  'alloy ingots',
  'alloying additives',
  'armor-grade plate lots',
  'atmospheric survey logs',
  'bar and rod stock',
  'basalt fiber feedstock',
  'Beira ice blocks',
  'bespoke medical nutriments',
  'billet stock',
  'blasting charges',
  'Bluefire isotope cylinders',
  'bonded contractor crew',
  'bonded Guild line-check freight',
  'bonded water tanks',
  'brokered Pike nickel-iron ingots',
  'Bruckner branch resupply pallets',
  'Bruckner field technician team',
  'bulk industrial chemicals',
  'bulk ration packs',
  'bulk silicates',
  'bulk worker supply pallets',
  'bulk-food allotments',
  'carbon-fiber structural rolls',
  'Carbonvale export lots',
  'cargo-frame stock',
  'casting blanks',
  'Celadon-class acceptance records',
  'Celadon-class docking collar assemblies',
  'Celadon-class highliner frame interface rings',
  'Celadon-class hull elements',
  'Celadon-class luxury liner modules',
  'Celadon-class pressure-shell sections',
  'Celadon-class registry vault',
  'Celadon-class signature shell modules',
  'certification audit packets',
  'certified clean-metal lots',
  'certified drive overhaul kits',
  'certified duel referees',
  'certified frame members',
  'certified low-carbon plate stock',
  'certified main-drive cores',
  'certified maneuvering engine units',
  'certified Pike ballast slabs',
  'certified pressure gas cylinders',
  'certified propulsion service stock',
  'certified refit modules',
  'certified robotic destriers',
  'certified steel stock',
  'certified weld stock',
  'challenge writs and bout stakes',
  'Cinderhook pressure-alloy billets',
  'Cinnabar trace-metal lots',
  'claims office passenger party',
  'clean ballast slabs',
  'clean volatile lots',
  'client specification archive',
  'client specification archives',
  'cobalt ingots',
  'coke and flux',
  'commissioning engineer team',
  'completed long-term shift returnees',
  'compressor cartridge crates',
  'corrosion-shield laminate blanks',
  'crest-coded transponder petitions',
  'crusher modules',
  'cryo pump skids',
  'cryo-safe valve kits',
  'cryo-safe valve racks',
  'cultured game-bird cuts',
  'custody processing passengers',
  'custody transfer passengers',
  'dealer compliance auditors',
  'deep-pressure valve assemblies',
  'Dense machine parts',
  'disassembled siege engine kits',
  'docking collar rework assemblies',
  'drill head assemblies',
  'drill stock',
  'drive alignment certification kits',
  'drive alignment crew',
  'duelists, seconds, and armor squires',
  'emergency oxygen bottles',
  'emergency patch kits',
  'emergency propulsion service crew',
  'engine overhaul kits',
  'executive and supervisor staff',
  'executive delegation',
  'executive fitting delegation',
  'executive inspection party',
  'exterior fairing panels',
  'factory-certified main drive module',
  'failed drive service returns',
  'family blade blanks',
  'fastener stock',
  'ferrochrome ingots',
  'field geometry incident team',
  'finished machinery',
  'fit-out module crates',
  'fluxing agents',
  'frame members',
  'frontier ration lockers',
  'furnace consumables',
  'gas-giant coolant stock',
  'gas-giant corrosion shielding panels',
  'gas-giant shielding laminate blanks',
  'gear assemblies',
  'graduated household guard cadres',
  'grain rations',
  'graphene cable stock',
  'graphite heat-sink blocks',
  'Guild apprentice passage warrant',
  'Guild certification telemetry kit',
  'habitat sealant drums',
  'Hartwell clean-metal lots',
  'Hartwell return rotation',
  'Hartwell worksite crew block',
  'heavy machinery',
  'heavy vehicle chassis',
  'helium-rich industrial gas racks',
  'heraldic evidence chests',
  'heraldic hull plate patterns',
  'heralds with sealed precedence rolls',
  'high-finish pressure alloy lots',
  'high-grade alloy ore',
  'high-purity ingots',
  'hoist drum assemblies',
  'house banner target automata',
  'house yacht refit bonds',
  'household guard candidates',
  'household guards in dress kit',
  'hull acceptance board',
  'hull plate stock',
  'hull warranty packets',
  'hydrocarbon separator skids',
  'imported machine parts',
  'imported refractory feedstock',
  'incident review board',
  'industrial lubricant drums',
  'industrial oxygen bottles',
  'industrial sulfur lots',
  'instrument-grade alloy',
  'instrument-grade alloy blanks',
  'instrument-grade Hartwell alloy blanks',
  'interior finish inspectors',
  'interior module lots',
  'iron-ore pellets',
  'Junior Teamster passage warrant',
  'Keelwright component overruns',
  'Kisaragi master shipwright delegation',
  'Kisaragi recovery rotation crew',
  'life-support filter pallets',
  'Light sealed freight',
  'long-term Hartwell shift cohort',
  'low-carbon plate feedstock',
  'low-grade titanium tailings concentrate',
  'luxury liner module rework lots',
  'Macao debt-court ice',
  'machine tools',
  'machine-tool stock',
  'main drive maintenance supplies',
  'Marcher mineral salts',
  'Marisma hydrocarbon fractions',
  'marriage exchange gifts',
  'marriage-contract notaries',
  'matching shell sections',
  'medical return passengers',
  'methane tankage',
  'metric-drive audit team',
  'metric-drive dealer inventory',
  'mining supplies',
  'nickel-iron ingots',
  'noble-table protein lots',
  'off-world alloy stock',
  'ore sorter modules',
  'organic solvent lots',
  'outer-spec hull plate stock',
  'owner representative party',
  'Paradiso hospitality cargo',
  'personnel transfers',
  'petition counsel and clerks',
  'petition counsel and sealed clerks',
  'Pike sulfide concentrate',
  'pilgrim scholars in sealed luxury berths',
  'plan directives',
  'plate and sheet stock',
  'plate steel',
  'platinum-group metal ingots',
  'polymer precursor drums',
  'precedence case witnesses',
  'precision alloy billets',
  'precision frame castings',
  'prefabricated modules',
  'prefabricated structural modules',
  'preserved-food crates',
  'pressure gas bottle pallets',
  'pressure seals and valve blocks',
  'pressure-alloy billets',
  'pressure-chain equipment pallets',
  'pressure-door frames',
  'pressure-door rework frames',
  'pressure-mined rare metal pallets',
  'pressure-pipe stock',
  'pressure-rated compressors',
  'pressure-shell blanks',
  'pressure-shell rework lots',
  'pressure-shell sections',
  'pressure-suit consumables',
  'private researchers with an unusually lavish retinue',
  'private stateroom fittings',
  'processed ore preforms',
  'production returns',
  'promenade fit-out crates',
  'promenade module lots',
  'proofed honor blades',
  'proofed siege engine carriages',
  'proofed structural billets',
  'proofed yacht components',
  'protein rations',
  'pump skid packages',
  'pumps and compressors',
  'quota allocations',
  'quota reports',
  'rail and beam stock',
  'rare-earth concentrate',
  'rare-element assay drums',
  'rare-metal export staging pallets',
  'RCS maintenance supplies',
  'recycler pump cartridges',
  'reduced-metal billet lots',
  'reduced-metal ingots',
  'refined metal ingots',
  'refinery frame reinforcement lots',
  'refinery maintenance skids',
  'refining reagents',
  'refractory brick',
  'refractory linings',
  'refractory ore',
  'registry and fit-out records',
  'regolith aggregate',
  'regolith shielding blocks',
  'rejected-but-saleable fittings',
  'replacement cutting heads',
  'replacement scrubber beds',
  'robotic destrier cradles',
  'rolled structural sections',
  'rotary bearing kits',
  'scrap charge',
  'scrap pressure alloy',
  'sculpted hunting beasts',
  'sealed antimatter precursor canisters',
  'sealed audit records',
  'sealed chancery bundles',
  'sealed debt-ledger records',
  'sealed export-lien packets',
  'sealed Guild insurance archives',
  'sealed legal archives',
  'sealed orbital maneuvering engine package',
  'sealed petition archive',
  'sealed title packets',
  'sealed warranty replacement lots',
  'sealed yard acceptance papers',
  'senior commissioning crew',
  'shareholder packets',
  'Shielded dense cargo',
  'shielded isotope concentrates',
  'shift rotations',
  'shipwright witnesses and appraisers',
  'shipyard machine-tool stock',
  'shock-lance racks',
  'shoring timber',
  'silica crystal stock',
  'skim condensate canisters',
  'smelter electrodes',
  'smelter feedstock',
  'specialty ore',
  'spent-tooling returns',
  'stable fuel canisters',
  'staged precursor lot',
  'Standard container freight',
  'steel billets',
  'storm-forecast data',
  'structural billets',
  'structural components',
  'sulfide byproduct drums',
  'sulfur clinker',
  'sulfur-rated loader frames',
  'surface hydrogen ration tanks',
  'surface labor allocation',
  'technical specialist party',
  'thermal-control maintenance kits',
  'Tinto smelter cakes',
  'titanium tailings concentrate',
  'tool-steel stock',
  'tooling and spares',
  'tournament armor aftercare crates',
  'unfinished hull sections',
  'vacuum loader kits',
  'valve control kits',
  'VHM civilian drive inventory',
  'VHM factory engineer delegation',
  'VHM propulsion core assembly',
  'warranty arbitration board',
  'warranty inspector party',
  'welded assemblies',
  'work crews',
  'work rotations',
  'workforce transfer group',
  'workforce transfer manifests',
  'worksite battery stacks',
  'yard acceptance documents',
  'yard arbitration counsel',
  'yard tooling pallets',
  'bagged silicate feedstock',
  'bagged sulfide concentrate lots',
  'ballast-grade refinery feed',
  'chromite ore',
  'Cinderhook nickel-iron feedstock',
  'clean pressure-metal billets',
  'clean pressure-metal feedstock',
  'cobalt ore',
  'cut ballast export slabs',
  'cutting heads',
  'House delegation',
  'life-support consumables',
  'magnesium-aluminum refinery feed',
  'magnesium-aluminum silicate lots',
  'metallurgical experts',
  'nickel concentrate',
  'nickel ingots',
  'nickel-iron ore',
  'orbital nickel-iron export lots',
  'oxygen canisters',
  'Pike nickel-iron ingots',
  'platinum-group ingots',
  'platinum-group ore',
  'pressure-metal export lots',
  'rare-earth oxides',
  'rare-earth-bearing ore',
  'ration packs',
  'reduced metal export lots',
  'reduced-metal billets',
  'reduced-metal refinery feed',
  'refinery crew rotations',
  'refinery crews',
  'refinery executives',
  'shift crews',
  'shoring frames',
  'sulfide refinery concentrate',
]);

function catalogLabel(label: string): string {
  if (FRAGILE_CARGO[label] || ORDINARY_CARGO.has(label)) return label;
  const tierless = label.replace(/^(Silk|Porcelain|Celadon)-class /, '');
  return tierless;
}

function cargoTypeId(label: string): string {
  return label.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

/** Apply the explicit Estella cargo-handling catalog to a generated manifest. */
export function classifyMissionCargo(cargo: MissionCargoSpec): MissionCargoSpec {
  const key = catalogLabel(cargo.label);
  if (FRAGILE_CARGO[key] === undefined && !ORDINARY_CARGO.has(key)) {
    throw new Error(`Unclassified Estella cargo type: ${cargo.label}`);
  }
  const fragile = FRAGILE_CARGO[key];
  return { ...cargo, cargoTypeId: cargo.cargoTypeId ?? cargoTypeId(cargo.label), fragile };
}

export function fragilityDisplay(terms: FragileCargoTerms): string {
  const level = FRAGILITY_LEVELS[terms.level].name;
  return terms.shockAbsorbingContainer ? `${level} (in a shock-absorbing container)` : level;
}

export function isCatalogedCargoLabel(label: string): boolean {
  const key = catalogLabel(label);
  return FRAGILE_CARGO[key] !== undefined || ORDINARY_CARGO.has(key);
}

export const ESTELLA_CARGO_CATALOG_SIZE = Object.keys(FRAGILE_CARGO).length + ORDINARY_CARGO.size;
